Update deploy-flaskApp.yaml

diff --git a/.github/workflows/deploy-flaskApp.yaml b/.github/workflows/deploy-flaskApp.yaml
--- a/.github/workflows/deploy-flaskApp.yaml
+++ b/.github/workflows/deploy-flaskApp.yaml
@@ -87,14 +87,17 @@ jobs:
           echo "Minikube IP: $minikube_ip"
           echo "MINIKUBE_IP=$minikube_ip" >> $GITHUB_ENV
       # Get Minikube IP and port where the Flask app is exposed
+      # Get Minikube IP and Flask app URL
       - name: Get Flask app URL
         run: |
-          minikube_ip=${{ env.minikube_ip }}
+          minikube_ip=$(minikube ip)  # Assign minikube IP properly
           minikube_service_port=$(kubectl get svc flask-app-service -o=jsonpath='{.spec.ports[0].nodePort}')
+    
+          if [ -z "$minikube_ip" ]; then
+             echo "Error: Minikube IP is empty!"
+             exit 1
+          fi
+
+          # Output the Flask app URL and set it as environment variable
           echo "Flask app is available at http://$minikube_ip:$minikube_service_port"
-          echo "Flask app is available at http://$minikube_ip:$minikube_service_port" >> $GITHUB_ENV
-          
-      # Show Flask app URL
-      - name: Show Flask app URL
-        run: |
-          echo "Flask app is available at http://${{ env.minikube_ip }}:${{ env.minikube_service_port }}"
+          echo "FLASK_APP_URL=http://$minikube_ip:$minikube_service_port" >> $GITHUB_ENV
